services:
  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PORT
        value: 5173  # Ensure this matches the port in vite.config.js
